refactor: Replace location determination with common-rs crate
mozilla-services/contile pull request #219
Opened 2021-07-21 22:58 UTC by mythmon

## Description

The location parsing code that Contile had was useful, so I stole it to put into https://github.com/mozilla-services/common-rs/pull/14. This PR re-integrates that code as an external crate. Note that this is currently pulling the crate straight from that PR. That means the other PR should merge and this PR should be updated to point to crates.io before we merge this PR.

This drops support for GCS provided location headers, which are not being used currently. We should consider adding that feature to the shared crate as well.

## Testing

MaxMind based location should work exactly the same as before. Non-location features should be unaffected.

2021-07-24 00:00 UTC, pjenvey requested changes
Needs a small update for the latest main

2021-08-16 18:55 UTC, pjenvey submitted a review, later dismissed
Sorry @mythmon I totally missed the last update. 

I've fixed the merge conflicts here: https://github.com/mozilla-services/contile/tree/extract-location-merge

Shall I push that merge to your branch?

2021-08-16 19:57 UTC, mythmon commented
Yes please. Thanks for doing the merge again.

2021-08-16 20:21 UTC, jrconlin approved these changes

2021-08-16 21:50 UTC, merged