chore: cleanup bucket creation
mozilla-services/contile pull request #245
Opened 2021-08-05 19:51 UTC by jrconlin

## Description

* remove unused code
* added comment describing bucket properties
* removed unused setting
* changed function name to `check_bucket`

## Testing

How should reviewers test?

## Issue(s)

Closes [link](link).

2021-08-05 21:52 UTC, pjenvey requested changes
don't forget to remove the now unused `create_bucket` setting

2021-08-05 21:53 UTC, pjenvey commented on src/server/img_storage.rs
> +#[serde(default)]
👍

2021-08-05 22:13 UTC, jrconlin commented
right,forgot to drop that with one of the stashes.

2021-08-06 23:50 UTC, pjenvey approved these changes

2021-08-09 23:56 UTC, merged