docs: Add test & debugging doc
mozilla-services/contile pull request #451
Opened 2022-09-13 15:31 UTC by jrconlin

Add doc describing using contract testing for local debugging.

2022-09-15 21:08 UTC, Trinaa commented
@jrconlin 

As discussed, I attempted merged TESTING.MD with the contract test READMEs. Let me know your thoughts on the 'Local Execution and Debugging' sections.

I'm still pondering about adding instructions for running contract tests individually and maybe to add a 'Local Execution and Debugging' section to the client README

2022-10-03 23:49 UTC, pjenvey requested changes

2022-10-03 23:49 UTC, pjenvey commented on test-engineering/contract-tests/client/README.md
> +    In the Contile definition, expose port 5000 by adding the following:
```suggestion
    In the Contile definition, expose port 8000 by adding the following:
```

2022-10-03 23:49 UTC, pjenvey commented on test-engineering/contract-tests/client/README.md
> +    ```text
Note you could also use **```shell** on these

2022-10-07 00:33 UTC, pjenvey requested changes
Sorry I missed this one last week, looks good otherwise

2022-10-07 00:33 UTC, pjenvey commented on test-engineering/contract-tests/README.md
> +    -H "UserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:10.0) Gecko/20100101 Firefox/91.0'" \
Or there's also `-A` (which I rarely use)

```suggestion
    -H "User-Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:10.0) Gecko/20100101 Firefox/91.0'" \
```

2022-10-07 17:52 UTC, pjenvey approved these changes

2022-10-11 19:34 UTC, tiftran approved these changes
Looks good to me!

2022-10-11 19:34 UTC, tiftran commented on test-engineering/contract-tests/README.md
> +**Build Contile Docker Image**
thank you for documenting this 🙂 now my newbie docker self can stop editing docker-compose and accidentally commit it now 🙃

2022-10-24 16:05 UTC, merged