[DISCO-2370] Add pull request template to Contile
mozilla-services/contile pull request #535
Opened 2023-04-27 15:25 UTC by Trinaa

## References

JIRA: [DISCO-2370](https://mozilla-hub.atlassian.net/browse/DISCO-2370)
GitHub: #534 

## Description

Proposal to add a PR template to this project. All ideas, modifications and suggestions welcome!

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/contile/blob/main/CONTRIBUTING.md)
- [ ] This PR conforms to the [Opsec policies](https://github.com/mozilla-services/websec-check)
- [ ] Functional and performance test coverage has been expanded and maintained 
- [ ] Documentation has been updated
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title

[DISCO-2370]: https://mozilla-hub.atlassian.net/browse/DISCO-2370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-27 16:12 UTC, linabutler approved these changes
Stamp!

2023-05-01 22:08 UTC, pjenvey requested changes

2023-05-01 22:08 UTC, pjenvey commented on PULL_REQUEST_TEMPLATE.md
> +GitHub: [#TODO](https://github.com/mozilla-services/merino-py/issues/TODO)
```suggestion
GitHub: [#TODO](https://github.com/mozilla-services/contile/issues/TODO)
```

2023-05-03 14:51 UTC, Trinaa commented on PULL_REQUEST_TEMPLATE.md
> +GitHub: [#TODO](https://github.com/mozilla-services/merino-py/issues/TODO)
🤦🏻‍♀️ TY for the catch @pjenvey

2023-05-03 15:57 UTC, Trinaa commented
@pjenvey Could you take another look?

2023-05-03 16:58 UTC, merged